# Generated by Django 5.0.8 on 2025-03-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_elementcitation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcitation',
            name='marked_xml',
            field=models.TextField(blank=True, verbose_name='Marked XML'),
        ),
    ]
