apiVersion: v1
kind: Service
metadata:
  name: markapi-hml-postgres
  namespace: markapi-hml
  labels:
    app: markapi-hml-postgres
  annotations:
  selfLink: /api/v1/namespaces/markapi-hml/services/markapi-hml-postgres
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: markapi-hml-postgres
  clusterIP:
  clusterIPs:
  type: ClusterIP
  sessionAffinity: None
