apiVersion: v1
kind: Service
metadata:
  name: markapi-hml-django-svc
  namespace: markapi-hml
  labels:
    app: markapi-hml-django
  selfLink: /api/v1/namespaces/markapi-hml/services/markapi-hml-django-svc
spec:
  ports:
    - name: webapp
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort:
  selector:
    app: markapi-hml-django
  clusterIP:
  clusterIPs:
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
