apiVersion: apps/v1
kind: Deployment
metadata:
  name: markapi-hml-celerybeat
  namespace: markapi-hml
  generation: 1
  labels:
    app: markapi-hml-celerybeat
    k8slens-edit-resource-version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
  selfLink: /apis/apps/v1/namespaces/markapi-hml/deployments/markapi-hml-celerybeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markapi-hml-celerybeat
  template:
    metadata:
      labels:
        app: markapi-hml-celerybeat
    spec:
      volumes:
        - name: markapi-hml-django-media
          persistentVolumeClaim:
            claimName: markapi-hml-django-media-pvclaim
        - name: markapi-hml-django-tmp
          persistentVolumeClaim:
            claimName: markapi-hml-django-tmp-pvclaim
      containers:
        - name: webapp
          image: scieloorg/markapi:v0.1.0
          command:
            - /start-celerybeat
          envFrom:
            - configMapRef:
                name: configmap-markapi-hml
          resources: {}
          volumeMounts:
            - name: markapi-hml-django-media
              mountPath: /app/core/media
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: app
          operator: Equal
          value: producao
          effect: NoSchedule
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
