apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: markapi-hml
  labels:
    app: redis
  annotations:
  selfLink: /api/v1/namespaces/markapi-hml/services/redis
spec:
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  clusterIP:
  clusterIPs:
  type: ClusterIP
  sessionAffinity: None
