# Generated by Django 5.0.8 on 2025-08-25 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMLDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_file', models.FileField(help_text='Upload an XML file for processing.', upload_to='xml_manager/xml/', verbose_name='XML File')),
                ('validation_file', models.FileField(blank=True, null=True, upload_to='xml_manager/csv/', verbose_name='Validation File')),
                ('exceptions_file', models.FileField(blank=True, null=True, upload_to='xml_manager/exceptions/', verbose_name='Exceptions File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the file was uploaded.', verbose_name='Uploaded At')),
            ],
        ),
        migrations.CreateModel(
            name='XMLDocumentHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_file', models.FileField(upload_to='xml_manager/html/', verbose_name='HTML File')),
                ('language', models.CharField(default='pt', help_text='Language code or name', max_length=32, verbose_name='Language')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('xml_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='htmls', to='xml_manager.xmldocument', verbose_name='XML Document')),
            ],
        ),
        migrations.CreateModel(
            name='XMLDocumentPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='xml_manager/pdf/', verbose_name='PDF File')),
                ('language', models.CharField(default='pt', help_text='Language code or name', max_length=32, verbose_name='Language')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('xml_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='xml_manager.xmldocument', verbose_name='XML Document')),
            ],
        ),
    ]
