# Generated by Django 5.0.8 on 2025-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xmldocument',
            options={'verbose_name': 'XML Document', 'verbose_name_plural': 'XML Documents'},
        ),
        migrations.AlterModelOptions(
            name='xmldocumenthtml',
            options={'verbose_name': 'XML Document HTML', 'verbose_name_plural': 'XML Document HTMLs'},
        ),
        migrations.AlterModelOptions(
            name='xmldocumentpdf',
            options={'verbose_name': 'XML Document PDF', 'verbose_name_plural': 'XML Document PDFs'},
        ),
        migrations.AlterField(
            model_name='xmldocument',
            name='exceptions_file',
            field=models.FileField(blank=True, null=True, upload_to='xml_manager/validation/', verbose_name='Exceptions File'),
        ),
        migrations.AlterField(
            model_name='xmldocument',
            name='validation_file',
            field=models.FileField(blank=True, null=True, upload_to='xml_manager/validation/', verbose_name='Validation File'),
        ),
    ]
