# Generated by Django 5.0.8 on 2025-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_manager', '0002_alter_xmldocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldocumentpdf',
            name='docx_file',
            field=models.FileField(blank=True, help_text='Intermediate DOCX file generated during PDF creation', null=True, upload_to='xml_manager/docx/', verbose_name='DOCX File'),
        ),
    ]
