# Generated by Django 5.0.8 on 2025-08-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        ('xml_manager', '0002_alter_xmldocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLDocumentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('error_type', models.CharField(blank=True, choices=[('VDE', 'XML Validation Error'), ('CDE', 'XML Conversion to DOCX Error'), ('CPE', 'XML Conversion to PDF Error'), ('CTE', 'XML Conversion to TEX Error')], max_length=3, null=True, verbose_name='Error Type')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('handled', models.BooleanField(default=False, verbose_name='Handled')),
                ('creator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('xml_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_manager.xmldocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
