# Generated by Django 5.0.8 on 2025-08-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_xmldocumentevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnexpectedEvent',
            new_name='GeneralEvent',
        ),
        migrations.RenameIndex(
            model_name='generalevent',
            new_name='tracker_gen_excepti_7389c9_idx',
            old_name='tracker_une_excepti_47ede4_idx',
        ),
        migrations.RenameIndex(
            model_name='generalevent',
            new_name='tracker_gen_item_77b66a_idx',
            old_name='tracker_une_item_795336_idx',
        ),
        migrations.RenameIndex(
            model_name='generalevent',
            new_name='tracker_gen_action_1474c9_idx',
            old_name='tracker_une_action_55cd4b_idx',
        ),
    ]
