# Generated by Django 5.0.8 on 2025-08-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_unexpectedevent_generalevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xmldocumentevent',
            options={'verbose_name': 'XML Document Event', 'verbose_name_plural': 'XML Document Events'},
        ),
        migrations.AlterField(
            model_name='xmldocumentevent',
            name='error_type',
            field=models.CharField(blank=True, choices=[('XPE', 'XML Parsing Error'), ('VDE', 'XML Validation Error'), ('CDE', 'XML Conversion to DOCX Error'), ('CPE', 'XML Conversion to PDF Error'), ('CTE', 'XML Conversion to TEX Error')], max_length=3, null=True, verbose_name='Error Type'),
        ),
    ]
