# Generated by Django 5.0.8 on 2025-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_xmldocumentevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmldocumentevent',
            name='error_type',
            field=models.CharField(blank=True, choices=[('XPE', 'XML Parsing Error'), ('VDE', 'XML Validation Error'), ('CDE', 'XML Conversion to DOCX Error'), ('CHE', 'XML Conversion to HTML Error'), ('CPE', 'XML Conversion to PDF Error'), ('CTE', 'XML Conversion to TEX Error'), ('UNE', 'Unknown Error')], max_length=3, null=True, verbose_name='Error Type'),
        ),
    ]
